openapi: 3.0.3
info:
  title: Future Muscle Partner API
  description: パーソナルトレーナーのマッチングサービスAPI
  version: 1.0.0
tags:
  - name: account
    description: アカウント管理
  - name: profile
    description: プロフィール
  - name: trainer
    description: パーソナルトレーナー
  - name: booking
    description: 予約
  - name: review
    description: レビュー
  - name: payment
    description: 決済
  - name: provider
    description: パーソナルトレーニング提供者
security:
  - Bearer: []
paths:
  /login:
    post:
      tags:
        - account
      summary: API-001 ログイン
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: ログインに成功しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /logout:
    post:
      tags:
        - account
      summary: API-002 ログアウト
      operationId: logout
      security: []
      responses:
        '200':
          description: ログアウトに成功しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /signup:
    post:
      tags:
        - account
      summary: API-003 会員登録
      operationId: signup
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: 会員登録に成功しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /account:
    delete:
      tags:
        - account
      summary: API-004 会員退会
      operationId: deleteAccount
      responses:
        '200':
          description: 会員退会に成功しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /profile:
    get:
      tags:
        - profile
      summary: API-005 自分のプロフィール表示
      operationId: getUserProfile
      responses:
        '200':
          description: プロフィールの取得に成功しました。
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    put:
      tags:
        - profile
      summary: API-006 プロフィール更新
      operationId: putUserProfile
      responses:
        '200':
          description: プロフィールの更新に成功しました。
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /trainers:
    get:
      tags:
        - trainer
      summary: API-007 パーソナルトレーナー検索
      operationId: searchTrainers
      security: []
      responses:
        '200':
          description: トレーナーの検索結果を取得しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /trainers/{trainer_id}/menu:
    get:
      tags:
        - trainer
      summary: API-008 トレーニングメニュー取得
      operationId: getTrainingMenu
      security: []
      parameters:
        - name: trainer_id
          in: path
          description: トレーナーのID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: トレーニングメニューを取得しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

  /trainers/{trainer_id}/profile:
    get:
      tags:
        - trainer
      summary: API-009 トレーナープロフィール取得
      operationId: getTrainerProfile
      security: []
      parameters:
        - name: trainer_id
          in: path
          description: トレーナーのID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: トレーナープロフィールを取得しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /trainers/{trainer_id}/reviews:
    get:
      tags:
        - trainer
      summary: API-010 トレーナー口コミ取得
      operationId: getTrainerReviews
      security: []
      parameters:
        - name: trainer_id
          in: path
          description: トレーナーのID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: トレーナーの口コミを取得しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /trainers/{trainer_id}/schedule:
    get:
      tags:
        - trainer
      summary: API-011 トレーナースケジュール取得
      operationId: getTrainerSchedule
      security: []
      parameters:
        - name: trainer_id
          in: path
          description: トレーナーのID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: トレーナーのスケジュールを取得しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /bookings:
    get:
      tags:
        - booking
      summary: API-012 予約済みトレーニング取得
      operationId: getBookings
      responses:
        '200':
          description: ユーザーの予約情報を取得しました。
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    post:
      tags:
        - booking
      summary: API-013 トレーニング予約（仮登録）
      operationId: bookTraining
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '200':
          description: 予約が仮登録されました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /bookings/{booking_id}:
    delete:
      tags:
        - booking
      summary: API-014 トレーニング予約削除
      operationId: deleteBooking
      parameters:
        - name: booking_id
          in: path
          description: 予約ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 予約が削除されました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /bookings/{booking_id}/confirm:
    post:
      tags:
        - booking
      summary: API-015 トレーニング予約（本登録）
      operationId: confirmBooking
      parameters:
        - name: booking_id
          in: path
          description: 予約ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingConfirmationRequest'
      responses:
        '200':
          description: 予約が本登録されました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /booking/{booking_id}/status:
    put:
      tags:
        - booking
      summary: API-016 トレーニング受講ステータス変更
      operationId: updateTrainingStatus
      parameters:
        - name: booking_id
          in: path
          description: 予約ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingStatusUpdateRequest'
      responses:
        '200':
          description: ステータスが更新されました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /payment:
    post:
      tags:
        - payment
      summary: API-017 決済
      operationId: makePayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: 決済が完了しました。
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServer'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /reviews:
    post:
      tags:
        - review
      summary: API-018 口コミ登録
      operationId: postReview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '200':
          description: 口コミ登録成功
  /reviews/{review_id}:
    put:
      tags:
        - review
      summary: API-019 口コミ修正
      operationId: putReview
      parameters:
        - name: review_id
          in: path
          description: 口コミID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '200':
          description: 口コミ修正成功
    delete:
      tags:
        - review
      summary: API-020 口コミ削除
      operationId: deleteReview
      parameters:
        - name: review_id
          in: path
          description: 口コミID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 口コミ削除成功
  /trainer:
    post:
      tags:
        - provider
      summary: API-021 トレーナー登録
      operationId: postTrainer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trainer'
      responses:
        '200':
          description: トレーナー登録成功
    put:
      tags:
        - provider
      summary: API-022 トレーナー属性更新
      operationId: putTrainer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trainer'
      responses:
        '200':
          description: トレーナー属性更新成功
  /training-menus:
    post:
      tags:
        - provider
      summary: API-023 トレーニングメニュー登録
      operationId: postTrainingMenu
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingMenu'
      responses:
        '200':
          description: トレーニングメニュー登録成功
  /training-menus/{menu_id}:
    put:
      tags:
        - provider
      summary: API-024 トレーニングメニュー更新
      operationId: putTrainingMenu
      parameters:
        - name: menu_id
          in: path
          description: メニューID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingMenu'
      responses:
        '200':
          description: トレーニングメニュー更新成功
    delete:
      tags:
        - provider
      summary: API-025 トレーニングメニュー削除
      operationId: deleteTrainingMenu
      parameters:
        - name: menu_id
          in: path
          description: メニューID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: トレーニングメニュー削除成功

components:
  schemas:
    ProblemDetailError:
      description: A Problem Details object (RFC 9457)
      type: object
      properties:
        title:
          type: string
          description: A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
          example: Service Unavailable
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
      example:
        title: Description of the type of problem that occurred
        status: 400 # HTTP response status, appropriate for the problem type
        detail: Description of specific occurrence of the problem

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: メールアドレス
        password:
          type: string
          format: password
          description: パスワード
    SignupRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: メールアドレス
        password:
          type: string
          format: password
          description: パスワード
        name:
          type: string
          description: 名前
    BookingRequest:
      type: object
      properties:
        menu_id:
          type: string
          description: トレーニングメニューのID
        trainee_id:
          type: string
          description: トレーニーID
        training_start_at:
          type: string
          format: date
          description: トレーニング開始日時
        training_end_at:
          type: string
          format: date
          description: トレーニング終了日時
    PaymentRequest:
      type: object
      properties:
        amount:
          type: number
          format: double
          description: 支払金額
        method:
          type: string
          description: 支払方法
    BookingConfirmationRequest:
      type: object
      properties:
        booking_id:
          type: string
          description: 予約のID
        booking_status_kbn:
          type: string
          description: 予約ステータス区分
    TrainingStatusUpdateRequest:
      type: object
      properties:
        booking_id:
          type: string
          description: トレーニングのID
        training_status_kbn:
          type: string
          description: トレーニングステータス区分
    Review:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
    Trainer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
    TrainingMenu:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
  responses:
    BadRequest:
      description: 400 Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetailError"
    Unauthorized:
      description: 401 Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetailError"
    Forbidden:
      description: 403 Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetailError"
    NotFound:
      description: 404 Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetailError"
    Conflict:
      description: 409 Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetailError"
    UnprocessableEntity:
      description: 422 Unprocessable Content
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetailError"
    InternalServer:
      description: 500 Internal Server
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetailError"
    ServiceUnavailable:
      description: 503 Service Unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetailError"
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Bearer トークン認証'
