openapi: "3.0.3"
info:
  version: 1.0.0
  title: Swagger Petstore
security:
  - Bearer: []
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - name: pets
    description: Everything about your Pets
paths:
  /pets:
    $ref: "./pets/pets.yaml"
  /pets/{pet_id}:
    $ref: "./pets/pets_pet_id.yaml"

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Authenthicaiton with bearer token'
