name: Test

on:
  pull_request:
    branches: [master]

jobs:
  java-html:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://pandoc/latex:2.9
      with:
        args: '"./documents/forJava/Javaコーディング規約.md" -s --self-contained --number-sections --toc -t html5 -c "./documents/common/pandoc_styles/css/style.css" -o "./documents/forJava/Javaコーディング規約.html"'
